### ISSUE TITLE
[Question]? Configuration is not read

### ISSUE THREAD

**Issue by eyp** [eirslett/frontend-maven-plugin#1158]
I'm trying just to run the `install-node-and-npm` goal.
Following the example project, if I configure the plugin like this:

```
                    <plugin>
				<groupId>com.github.eirslett</groupId>
				<artifactId>frontend-maven-plugin</artifactId>
				<!-- Use the latest released version:
                https://repo1.maven.org/maven2/com/github/eirslett/frontend-maven-plugin/ -->
				<version>1.15.0</version>

				<executions>
					<execution>
						<id>install node and npm</id>
						<goals>
							<!-- mvn frontend:install-node-and-npm -->
							<goal>install-node-and-npm</goal>
						</goals>
						<configuration>
							<nodeVersion>v17.9.1</nodeVersion>
						</configuration>
					</execution>
				</executions>

			</plugin>
```

I get this error:

    The parameters 'nodeVersion' for goal com.github.eirslett:frontend-maven-plugin:1.15.0:install-node-and-npm are missing or invalid

To avoid the issue and install the specified NodeJs version I need to move the `configuration` section outside the `execution`:

```
                      <plugin>
				<groupId>com.github.eirslett</groupId>
				<artifactId>frontend-maven-plugin</artifactId>
				<!-- Use the latest released version:
                https://repo1.maven.org/maven2/com/github/eirslett/frontend-maven-plugin/ -->
				<version>${frontend.maven.plugin.version}</version>

				<executions>
					<execution>
						<id>install node and npm</id>
						<goals>
							<!-- mvn frontend:install-node-and-npm -->
							<goal>install-node-and-npm</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<!-- See https://nodejs.org/en/download/ for latest node and npm (lts) versions -->
					<nodeVersion>v17.9.1</nodeVersion>
				</configuration>
			</plugin>
```

Also, I have a related problem with the other kind of goals like `npm`. It always does the default `install` command instead of reading the configuration I specified:

     mvn frontend:npm

```
<execution>
  <id>npm run eslint</id>
  <goals>
	<goal>npm</goal>
  </goals>
  <configuration>
	<arguments>run eslint</arguments>
  </configuration>
</execution>
```

    [INFO] Running 'npm install' in ...

**Comment by neoxpert** [comment]
I don't think this is purely and issue of the frontend plugin, but the way of how Maven works. A Maven build always consists of several phases (clean, compile, test-compile, test ..). Plugins may hook into those phases with several goals, like the compiler plugin attaching its _compile_ goal to the _compile_ phase and the _testCompile_ goal to the _test-compile_ phase.

Regarding the frontend plugin _install-node-and-npm_ and _npm_ are goals, that are bound to the _generate-resources_ phase be default. So if you would call _mvn generate-resources_ those goals would be executed. Adding an execution configuration could be used to bind these goals to another phase. Or offer additional configuration / execution steps for a certain goal.

By using or adding an execution step, you may rebind a goal to another phase. So instead of running the goal _install-node-and-npm_ you could make it to be executed within the _clean_ phase of maven. What the execution configuration do not do is overriding the configurations of a goal when calling it directly.

Calling _mvn frontend:install-node-and-npm_ will indeed invoke this exact goal offered by the plugin. But Maven will not lookup the configuration within the exeuction elements but the default plugin configuration. So having a basic configuration like this would work:

```xml
<plugin>
  <groupId>com.github.eirslett</groupId>
  <artifactId>frontend-maven-plugin</artifactId>
  <version>1.15.0</version>
  <configuration>
    <nodeVersion>v17.9.1</nodeVersion>
  </configuration>
</plugin>
```

Changing the configuration of the plugin to this one:

```xml
<plugin>
  <groupId>com.github.eirslett</groupId>
  <artifactId>frontend-maven-plugin</artifactId>
  <version>1.15.0</version>
  <executions>
    <execution>
      <id>install node and npm</id>
      <goals>
        <goal>install-node-and-npm</goal>
      </goals>
      <configuration>
        <nodeVersion>v17.9.1</nodeVersion>
      </configuration>
    </execution>
  </executions>
</plugin>
```

will cause _mvn frontend:install-node-and-npm_ to fail as the required nodeVersion is not configured for the direct invocation of the goal. If you would call it like _mvn frontend:install-node-and-npm -DnodeVersion=v17.9.1_ it would work again. Also calling _mvn generate-resources_ would work, as the execution step would tell Maven "hey, if we are at the install-node-and-npm goal, consider this configuration".
But what also would work, would be calling the _install-node-and-npm_ with an explicit identifier (that's what the <id></id> is for). _mvn frontend:install-node-and-npm@"install node and npm"_ (quoted due to the whitespaces in the id) would call the goal with the configuration stated in the given execution element.

**Comment by eyp** [comment]
Yes, I didn't mean it was an issue of the plugin (that's why I tagged it as a question). Thanks for the reply, it's useful.
