### ISSUE TITLE
Allow specific URL for npm and node installers

### ISSUE THREAD

**Issue by mosabua** [eirslett/frontend-maven-plugin#126]
It would be nice to have specific URLs as an option for the node and npm installers. This way you could host them e.g. internally in an organization on Apache or in a Nexus repo without having to replicate the structure of http://nodejs.org/dist/.

This is related to http://stackoverflow.com/questions/27289651/nexus-compliant-repository-to-get-node-and-npm-installers/

**Comment by Barnzy** [comment]
@msieurtoph How did you go about adding the 2 installers manually to a Nexus Site Repo? I've created the repo but haven't found a way of uploading a binary file.

**Comment by fhwrdh** [comment]
@Barnzy There may be multiple ways to do this, but I did not find a way to do it through the Nexus UI. We simply downloaded the necessary binaries to the machine and put them in the location on the file system used in our configuration. As @msieurtoph points out, the directory structure from nodejs.org must be replicated for this to work.

**Comment by msieurtoph** [comment]
@Barnzy: @fhwrdh is right. You have no other choice but manually put the files in the repository (I mean the physical folder on your drive/ftp).

And as long as the module does not support full pathes, you have to reproduce the directory structure of the original nodejs.org repository :

For instance, if your file comes from : `http://nodejs.org/dist/v0.12.0/x64/node.exe`
You got to create the same `/v0.12.0/x64/` structure in your personal repository

**Comment by mosabua** [comment]
You can upload the files into the right structure via http put requests or webdav. Directory creation has to happen via webdav as http does not support that.

**Comment by Barnzy** [comment]
@fhwrdh, @msieurtoph, @mosabua: Thank you all, extremely helpful. I felt like I was going mad looking for something in the Nexus UI. Will get onto the relevant department when I get back into work tomorrow to get the folder structure replicated on the Nexus box.

**Comment by eirslett** [comment]
I think you can get what you need in the newer versions of the plugin.

**Comment by tpischke** [comment]
This issue should be reopened.  The suggestion from @mosabua is good, but this is something the plugin should support directly without having to resort to hacking around in the nexus repo.  If we submit a patch to allow a full URL to be specified, would it be accepted?

**Comment by eirslett** [comment]
That problem with specifying a full URL (as opposed to only a download root) is that it breaks the premise of the plugin. It wouldn't be possible to use it on different OS-es, because with a full URL, everybody would get the same binary, while what is needed is that each OS gets its own binary compiled for that OS.
I think there is some work being done on gradle-node-plugin (a similar project) for fetching node.js directly from maven central (and also publishing all versions of node to maven central). Whenever that work is completed, we could add a m2 "repository layout" (a function from node version + os to download url) similar to the implicit "nodejs" repository layout we have today.
You could also checkout nodejs-maven-plugin, which uses nexus, as far as I can tell (I haven't tried it myself).
Or you could use maven-download-plugin to fetch node from your repository, given the full path, and then exec-maven-plugin to run the build tasks with the downloaded binary.

**Comment by tpischke** [comment]
Thanks for the thoughtful response.  I'll look into your suggestions, and look forward to the new version of your plugin with the m2 repository layout ;)

**Comment by mosabua** [comment]
With v3 of the Nexus Repository Manager you should be able to solve this problem now because you can proxy any site including e.g. the node.js download structure. This can be done with the raw repository format. Might be worth playing around with.

http://books.sonatype.com/nexus-book/3.0/reference/sites.html

**Comment by AdamBarnwell** [comment]
We are planning up upgrading to v3 very soon so this is very exciting news!
