### ISSUE TITLE
Option to skip installation if correct version already available system-wide

### ISSUE THREAD

**Issue by luanpotter** [eirslett/frontend-maven-plugin#170]
It would be nice to have a flag to skip installation of node, npm and bower if these are already installed globally in the exact same version as specified. This would be good so that normally nothing is downloaded, and yet it will work on all environments, and it would ideal for travis/shippable, as download the whole pack again and again slows the build down.

I tried to do it for a little while, and I thought the easiest way was to create the none/node with a simple script to redirect to the system's node, for example (same for others). It seemed to work, but I run into some troubles while running the npm (namely, my machine simply crashed, probably some recursive callback or something). I wouldn't know either if this solution would comply with the other OS's, as I'm not sure how bash scripts would run on those.

I'm willing to help, but before going any further, I'd like to know what you guys think about this idea, if there are already some workarounds or something like that, and if this is the best solution (create a reference to system wide version if present).

Of course it would be an option with default false, so if you are in a unbelievably wicked environment, and cannot be sure the node program is actually node, the current behavior is kept.

**Comment by eirslett** [comment]
Other people have asked about this before; the answer is to use maven-exec-plugin if you have installed node.js globally. Using this plugin, the build is slowed down somewhat because of the download, but the file is cached between builds so you only get that hit during the first build (just like Maven downloading dependencies)
Unfortunately, Travis wipes the working directory before each build, so it has to download Node every time - but the reason I don't want that functionality in the plugin, is to keep the complexity of the codebase down. (It's already growing too much, I think)
