### ISSUE TITLE
Add option to not fail build

### ISSUE THREAD

**Issue by iamplo** [eirslett/frontend-maven-plugin#172]
Hi, 
We have an established code base and we are just starting to integrate linting into our workflow. As you can imagine, jsHint throws a lot of errors and we want to give devs some time to address the problems. During this cleanup period we don't want the build failing on npm goals or grunt goals. Something like ```<failOnError>false</failOnError>```
FYI - we are using npm run to lint (not grunt) like so:
```html
                    <execution>
                        <id>npm lint</id>
                        <goals>
                            <goal>npm</goal>
                        </goals>
                      <configuration>
                           <arguments>run lint</arguments>
                        </configuration>
                    </execution>
```
package.json....
{
....
   "dependencies": {
      "jshint": "latest"
   },
    "scripts": {
        "lint": "jshint src/main/webapp/js --verbose"
  }...
Thanks for a great plugin!

**Comment by eirslett** [comment]
First a side note; it's better to do

`"lint": "node_modules/.bin/jshint src/main/webapp/js --verbose"`

then you ensure that you use the local version of jshint, and not the one on your PATH (they may not be the same)

To the point; your build is probably failing because jshint is returning a non-zero exit code.
I believe the build fails if you run "npm run line" from the command line, so it's not as much this plugin as it's the way npm is configured. You could do something like this, to try and force it to succeed:

`"lint": "node_modules/.bin/jshint src/main/webapp/js --verbose; true"`

`"lint": "node_modules/.bin/jshint src/main/webapp/js --verbose || true"`

Does that work?

Eventually, you could see if jshint has a flag:

`"lint": "node_modules/.bin/jshint src/main/webapp/js --verbose --ignore-failure"`

Something like that, which should return exit code 0 independent of lint result.
Or if it doesn't have that flag, send a PR to jshint.

A last solution I can think of is to write your own JavaScript file that you invoke via npm, and that script in turn calls jshint programmatically, and ignores failure.

**Comment by iamplo** [comment]
This worked
```"lint": "node_modules/.bin/jshint src/main/webapp/js --verbose || exit 0"```
Thanks for the advice and pointing me in the right direction
