### ISSUE TITLE
use system npm/node

### ISSUE THREAD

**Issue by ehartford** [eirslett/frontend-maven-plugin#177]
I want to use the system's node/npm instead of installing one because installing is slow.  But when I omit the install step, I get:

    java.io.IOException: Cannot run program ".../target/node/node" (in directory "...//target"): error=2, No such file or directory -> [Help 1]

though I know that npm/node is on the path.  Is there a way to use the system's node/npm instead of installing one?

**Comment by eirslett** [comment]
No, this plugin doesn't support that. Try using maven-exec-plugin instead!
(But installation shouldn't slow down the build; only the first time, then it caches the downloaded binaries)

**Comment by keithkml** [comment]
I'd like this as well – I would just enable it on our CI server to speed up our continuous build.

**Comment by eirslett** [comment]
There are a couple of things you can do:
1) Don't delete the ./node folder between builds - the executables are stored there, so they only have to be downloaded the first time.
or
2) Use the file:// protocol to specify a local node.js installation to "download", so you can skip the network IO time.
or
3) use maven-exec-plugin, which comes with its own problems
or
4) Host the binaries on a local proxy to reduce network IO
or
5) Live with it, there are usually other time thieves in the build-deployment process that take longer.

**Comment by jvmccarthy** [comment]
@eirslett Thanks for listing out the alternatives.  I've recently started using this excellent plugin, and I'm liking it a lot more than using the exec plugin for frontend builds.  This issue isn't a big problem for me personally, but I am curious if you would consider a pull request for either of these configuration enhancements,
  1. `useSystemIfPresent` - if true, the plugin will attempt to use commands from the system path first and fallback to downloading.
  2. `downloadToUserDir` - instead of downloading the `node` directory in each project, download node to a less volatile common directory such as `~/.m2`.  A child directory could be made for the plugin and each node version.  Build systems often like to start from a fresh copy to ensure the build integrity, and storing in the user directory seems like a less volatile alternative.

Thanks again for the plugin.

**Comment by eirslett** [comment]
1) I've already declined issues/PRs about that before (you'll have to dig in the archive though, to find them) - I think I've explained the reasons there.
2) For a long time, I considered adding an option like that; putting all the downloaded stuff in `~/.frontend-maven-plugin`, but I never got that far. The intention of putting it in the `node/` directory is that it is supposed to be cached between builds, so you don't get an increase in download time. The same goes with the node_modules folder, if you install lots of npm dependencies. If you decide to wipe out the folder anyway (e.g. on your build system) it still doesn't take that long to download, especially not if you're using a proxy. For local deveopment, people often run `mvn install` for incremental builds instead of `mvn clean install` (which is typically run on a build server) - they set up the `clean` task to remove the directory, but they don't run that task every time. So in that way, you get the best of both worlds - you can choose between a full build or a quicker incremental build.
But mind this - even if we downloaded everything into `~/.frontend-maven-plugin` (or wherever), that directory could just as well get "corrupted" than the `node/` directory, in fact more so, since a "full/clean build" wouldn't wipe out that directory and fix the problem. The one thing we would gain, is to be able to share node.js binaries between projects, so you wouldn't need 20 binaries lying around. (But then again, disk space is cheap, and node isn't really that big.)

**Comment by jvmccarthy** [comment]
Thanks for taking the time to provide feedback.  I've had similar thoughts about option 2.

**Comment by worldsayshi** [comment]
For anyone else arriving here looking for clues on how to speed up the build process using frontend-maven-plugin one thing that helped me slash a lot of build time was to exclude copying node_modules into `target`. I use the `warSourceExcludes` directive in `maven-war-plugin` for this. Confusingly enough there are many different exclude directives in war plugin but this one is the one that controls what is to be copied into target folder in the first place. The others control what is to be included into the war package.
```
  <plugin>
      <artifactId>maven-war-plugin</artifactId>
      <configuration>
          <dependentWarExcludes>WEB-INF/lib/*.jar</dependentWarExcludes>
          <warSourceExcludes>**/node_modules/**</warSourceExcludes>
          <archiveClasses>true</archiveClasses>
          <attachClasses>true</attachClasses>
      </configuration>
  </plugin>
```

**Comment by naderghanbari** [comment]
Even if being faster is not one's concern, having the option to use the system installed `node` is really expected from this plugin.
Most of similar plugins have such an option even as the default behavior, if you want to cache between builds, you can simply override the deault by saying something like `<downloadNode>true</downloadNode>`
