### ISSUE TITLE
npm config set registry <url> impact other node installation

### ISSUE THREAD

**Issue by cecchisandrone** [eirslett/frontend-maven-plugin#189]
Hello,

It seems that executing:

````
 <execution>
       <id>set npm registry</id>
       <goals>
          <goal>npm</goal>
       </goals>
       <configuration>
          <arguments>config set registry ${npm.registry.url}</arguments>
       </configuration>
 </execution>
````

affects the global .npmrc file and not the one inside node private folder. Is that normal?

**Comment by eirslett** [comment]
Try moving your .npmrc to the root folder (working directory) of the Maven project, does that help? (But I don't think it would be appropriate to use `npm config set` during the build, since that would modify stored configuration files.)

People usually specify a local registry in the npm mojo like this:

```xml
<arguments>install --registry=${npm.registry.url}</arguments>
```

does that work for you?

**Comment by cecchisandrone** [comment]
Yes. I've done that using local .npmrc file. Thanks!

**Comment by adityajk** [comment]
How to specify the credentials for the repo

**Comment by narayanai** [comment]
@adityajk, did you get any solution to specify credentials to registry? i am getting "401 unauthorized" error.
