### ISSUE TITLE
NPM root directory for windows has changes in v4

### ISSUE THREAD

**Issue by ByronLudwig** [eirslett/frontend-maven-plugin#290]
Hi,

The location to install node.js now has an x86/64 folder which is not accounted for in the install phase.
Adding a custom rootDirectory does not work as you seem to append the version at the end of the URL.

**Comment by Katharsas** [comment]
Yes, i also get this error:
`Could not download Node.js from: https://nodejs.org/dist/v4.1.1/x64/node.exe: Got error code 404 from the server.`

That is because the folder is not called "`x64`" for v4.x, but instead "`win-x64`". Maybe check for the version in `NodeAndNPMInstallAction#installNodeForWindows()` and add the prefix ?

File: https://github.com/eirslett/frontend-maven-plugin/blob/master/frontend-plugin-core/src/main/java/com/github/eirslett/maven/plugins/frontend/lib/NodeAndNPMInstaller.java

**Comment by eirslett** [comment]
I think this is the same issue that was fixed recently (if you look at the commit log). I just haven't gotten around to releasing the plugin yet...

**Comment by Katharsas** [comment]
Yes, i looked around and the new code in Platform.java looks good. So this is probably a duplicate.

**Comment by ByronLudwig** [comment]
Thanks guys did not see the closed tickets. This indeed seems fixed in the new commits. 

Duplicate of #276

**Comment by eirslett** [comment]
Aaaaaand I just released 0.0.26!
