### ISSUE TITLE
Use globally installed node-npm

### ISSUE THREAD

**Issue by vidyasagar-a** [eirslett/frontend-maven-plugin#340]
Can I use a globally installed node/npm for running other goals like bower, gulp, karma. I work behind a firewall and called have maven downloading and installing node.exe.

**Comment by adrianomedeirossantos** [comment]
Hello,

You can point your Node installation path  on <installDirectory/> parameter inside the <configuration> tag. 

I had a problem while doing that on Windows, NodeJS is installed on <<INSTALL_DIR>> /nodejs, but the frontend-maven plugin looks for Node on the path  <<INSTALL_DIR>>/node. As a workaround, I changed Node installation path of my machine to <<INSTALL_DIR>>/node and now works.

@eirslett

First of all, I would like to congrats you and all the contributors for this project! I would like to know if there is any reason to set NODE_WINDOWS="\\node\\node.exe" on the class InstallNodeExecutorConfig instead of NODE_WINDOWS="node.exe". For me, frontend-plugin does not need to specify how Node names its installation path. 

May I make a PR for this?

Best regards,

**Comment by eirslett** [comment]
First question; yes, you'll have to hack it together somehow. There's no way to directly use the globally installed version of node, for that you'll have to use exec-maven-plugin instead.
Second question: It's historically because of the way node.js handled windows binaries. I'm not sure if it's needed anymore - except for backwards compatibility!

**Comment by adrianomedeirossantos** [comment]
@eirslett 

It was not be the case of fixing the class InstallNodeExecutorConfig? This fix would make possible to use the global Node just setting the installDirectory. Am I correct?

**Comment by ette8899** [comment]
@adrianomedeirossantos 
I have same issue, I was wondering how did you rename your Node installation path?

**Comment by adrianomedeirossantos** [comment]
@ette8899 

In my case, NodeJS was installed on C:\Program Files\nodejs directory, so I had to change two things:

1. Rename C:\Program Files\nodejs to C:\Program Files\node.

2. On pom.xml, insert the value C:\Program Files\ on the installDirectory tag

**Comment by mancioshell** [comment]
As @adrianomedeirossantos said could be very useful if this plugin allow to use global NodeJS by setting the installDirectory to it.

**Comment by eirslett** [comment]
If multiple developers are building the project, each developer has installed Node.js on a different location, or developers are on different operating systems (some mac, some linux, some windows) then you cannot hardcode the installDirectory.

**Comment by mancioshell** [comment]
@eirslett Right! What i meant is remove default appending of INSTALL_PATH on `com.github.eirslett.maven.plugins.frontend.lib.NodeAndNPMInstaller`. This, should allow developer to set absolute path of installDirectory without consider "node" as last child path.

**Comment by adrianomedeirossantos** [comment]
@mancioshell That was my point! We don't need to consider "node" as last child path .

**Comment by yelhouti** [comment]
I used `mklink /D node .` to create a SymLink inside the folder  `C:\Program Files\nodejs` and I used it like this: `<installDirectory>C:\Program Files\nodejs</installDirectory>` also it would be great to fix this as explained previously

**Comment by gabyzaaf** [comment]
Hello I am using a proxy and do you know if it's possible to override the link for download the node (version) ? Thanks you

**Comment by mriehema** [comment]
Just read the README:
https://github.com/eirslett/frontend-maven-plugin#installing-node-and-npm
` <nodeDownloadRoot>http://myproxy.example.org/nodejs/</nodeDownloadRoot>`

**Comment by wayupthere** [comment]
To expand on @yelhouti's comment you can do the same thing `mklink /D node "C:\Program Files\nodejs"` in your project root directory and forego adding the installDirectory config to the maven file.
