### ISSUE TITLE
Plugin not work with FreeBSD

### ISSUE THREAD

**Issue by danielsoro** [eirslett/frontend-maven-plugin#409]

**Comment by eirslett** [comment]
That's correct. It only works on Windows, OS X and Linux.

**Comment by danielsoro** [comment]
No plan to support it?

**Comment by eirslett** [comment]
No, there is no plan to support it. I have no access to a FreeBSD system, and Travis CI doesn't support FreeBSD for automated testing, it looks like there are no available binaries on https://nodejs.org, and I don't think there are very many people who use FreeBSD who would benefit from it.

I suggest that you use maven-exec-plugin instead, follow this guide:
https://addyosmani.com/blog/making-maven-grunt/

**Comment by Weltraumschaf** [comment]
I would benefit from that, too.

**Comment by bugreporter0** [comment]
Can somewhat be used on FreeBSD by declaring local installation of npm/node. One would need to copy the installation from /usr/local, both node_modules and node/npm binaries, into some ~/.tmp/node and then declare installDirectory as "~/.tmp". For some strange reason, plugin uses $installDirectory/node/, so default install could not be used.

Linux compatibility layer helps to keep things building as well, but it has its own problems.

Also, am upset about lack of proper freebsd support *and* lack of support for proper system-wide installation of node/npm.

**Comment by elnicko** [comment]
This is just a follow-up for future reference. 

The plugin does not work out of the box.
```
./node -v 
ELF binary type "3" not known.
```

However, the fix is very simple, non-intrusive and does not require having to mess around with a locally installed node. The following is tested on FreeBSD 14.

It is sufficient to install/enable the linux binary compatibility layer. The following commands are necessary:
```
sysrc linux_enable="YES"
service linux start
pkg install linux_base-rl9
```

Running the same node command now yields:
```
./node -v                 
v22.14.0
```
