### ISSUE TITLE
Use npm version provided with node if not specified

### ISSUE THREAD

**Issue by ufoscout** [eirslett/frontend-maven-plugin#458]
Hi all,

The current configuration of the install-node-and-npm goal requires both the node and the npm versions. This forces to manually check what is the npm version provided with a specific node release and to update both the values. However, nodejs is already packaged with a specific version of npm. Would it be possible to use the npm version provided by default by node if the npmVersion is omitted?

For example, in this case:

```
    <execution>
        <id>install node and npm</id>
        <goals>
            <goal>install-node-and-npm</goal>
        </goals>
        <configuration>
            <nodeVersion>v6.2.2</nodeVersion>
            <npmVersion>3.9.5</npmVersion>
        </configuration>
    </execution>
```

it will use node 6.2.2 and npm 3.9.5. While in this case:

```
    <execution>
        <id>install node and npm</id>
        <goals>
            <goal>install-node-and-npm</goal>
        </goals>
        <configuration>
            <nodeVersion>v6.2.2</nodeVersion>
        </configuration>
    </execution>
```

it will use node 6.2.2 and whatever npm version provided with it.

**Comment by eirslett** [comment]
In the Windows case, npm isn't packaged with node, it has to be downloaded separately.
(At least that was the case when the plugin was written)

**Comment by stevenbower** [comment]
I have a patch that allows for this... Will post shortly.. It does look like NPM is provided from around the 4.x line and above on all platforms.. (i've confirmed on windows/linux but it looks from their docs this will be the case going forward).

**Comment by ndywicki** [comment]
Hi Guys,

We use the npm provided mode because we are behind a coorporate firewall who block node.exe download.
So without specify the `npmVersion` properties the plugin download the node tar.gz correctly.
It's great but the [npm install code](https://github.com/stevenbower/frontend-maven-plugin/commit/49b77ecc330873ea710dd2885076b1fda5f6cff7#diff-4b3b75f0c89bc476e9c26111e6a1e832R242) not copy the binaries under the node root directory like node.exe.

Result we have some warrning because it's the npm system used instead of the local project version:

```
[INFO] npm WARN lifecycle The node binary used for scripts is C:\workspaces\sample\node\node.exe 
but npm is using C:\Program Files\nodejs\node.exe itself. 
Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
```

Thanks

It's ok if we manually copies the binaries from `node/node_module/npm/bin/[npm,npm.cmd]` into `node/`
