### ISSUE TITLE
Extra 'node' folder getting injected to the installDirectory

### ISSUE THREAD

**Issue by aravinda777** [eirslett/frontend-maven-plugin#464]
I am using the plugin (v1.0) to trigger a gulp build. I am using the <installDirectory> setting to point to where my node installation is. I am not doing the node installation during the build as I am behind a firewall and there is no internal repo to point to. I see the plugin adding an extra 'node' directory to the path I provide and looking for the node.exe in that. The node.exe parent directory I have is not node. Else I would have given the previous directory and be done with it. I don't have rights to rename the folders either. Why is this extra 'node' folder getting added? Any way around this?

**Comment by eirslett** [comment]
For your use case, it is much better to use maven-exec-plugin:

https://addyosmani.com/blog/making-maven-grunt/

**Comment by aravinda777** [comment]
I found the front-end maven plugin to be a great fit for my task. It works perfectly for my use cases, but the only challenge was that node directory. Why aren't you directly using the directory path provided? Seems alike a very simple decision on the implementation side (?)

**Comment by eirslett** [comment]
The reason is that frontend-maven-plugin makes one important decision; it downloads node/npm locally for your project, and does not use the system provided version of node/npm. That is intentional, by design. People have managed to hack around it to make it use the system installations anyways, but it's against the plugin philosophy, and in no way officially supported. There are no guarantees that it will be bug-free ;-)
