### ISSUE TITLE
PLZ help me to include the plugin in grails framework

### ISSUE THREAD

**Issue by apple77y** [eirslett/frontend-maven-plugin#542]
First, I am sorry that this issue is not related to some kind of bugs.

I was wondering, if I could get an answer for the way to use it.

I've been trying to use this plugin in grails project, but I have a problem how to use it with groovy.

I guess that I should do with BuildConfig.groovy, not pom.xml.

``` groovy
...
grails.project.dependency.resolution = {
  ...
  dependencies {
    compile ('com.github.eirslett:frontend-maven-plugin:1.3')
  }
  ...
}
```

With this code, I could check that the plugin was clearly installed.

But I have no idea the way to convert the execution and configuration part with groovy.

Please tell me the guide to execute this plugin.

Thank you.

**Comment by eirslett** [comment]
If you use groovy, I suppose you use Gradle instead of Maven? The build config looks like Gradle config as well. (Else it would be pom.xml)

There is another plugin you can use, which does approximately the same thing as this plugin, except it's written for gradle/groovy: https://github.com/srs/gradle-node-plugin

Try using that one instead. Good luck!

**Comment by apple77y** [comment]
@eirslett 

I've found that the plugin you mention is in grails version 3.
However, our project's grails version is 2.4.3, which means there's no gradle in here.
Isn't there any other alternative way?

**Comment by eirslett** [comment]
I'm sorry, I don't really use/know grails or gradle, so I cannot help you with that.

**Comment by apple77y** [comment]
@eirslett 

Ok, then I will find the way. I really thank you for your answer.
