### ISSUE TITLE
Using globally installed node/npm

### ISSUE THREAD

**Issue by Ziker22** [eirslett/frontend-maven-plugin#574]
Hi,
Just wanted to ask is there a way to run plugin goals with globally installed node ?
i.e when running mvn generate-resources on some continous integration server such as Jenkins i want to  skip "instal-node-npm" goal and use node and npm installed on building machine during other goals (npm install, npm run build....)

**Comment by eirslett** [comment]
No, unfortunately that is not possible. Imagine that you have 2 projects, one using Node 4.x and another using Node 6.x. That will not be possible on your Jenkins server if you use the global node version, which will only be a single one, either 4.x or 6.x. So you may experience build failures that are difficult to debug.

**Comment by falkoner** [comment]
@eirslett proposing to reopen this feature request.

I would suggest to modify `install-node-npm` logic so that if it finds globally installed Node + NPM combination that matches versions requested in configuration, then it will use it instead of installing locally. And if it there are no global Node + NPM detected or version is different - then proceed with local installation as it is right now.

Justification: our build happens in docker container managed with Jenkins. So effectively each time we build the project there it has to checkout the project, download npm/node, fetch dependencies and build - just waste of time we'd like to avoid while preserving automatic installation for developers on their laptops. I'm fixing it here now with maven profiles, but would make sense to me to fix it on the plugin side, so that it uses global node and npm __if__ the versions are correct.

That also should address the concern you mentioned about multiple projects.
