### ISSUE TITLE
Maven's "Offline Mode" is not being honored

### ISSUE THREAD

**Issue by Deevian** [eirslett/frontend-maven-plugin#593]
When running a Maven build with the [offline option](http://books.sonatype.com/mvnref-book/reference/running-sect-options.html#running-sect-offline-option) ("--offline" or "-o") and with something like the following execution:

```
<execution>
    <id>npm install</id>
    <goals>
        <goal>npm</goal>
    </goals>
</execution>
```

The **frontend-maven-plugin** is ignoring the passed option and is allowing **npm** to fetch the dependencies from remote sources.

Ideally, all execution goals that require external dependencies should be skipped when the offline option has been passed by the user.

This was tested in version 1.3, but seems to remain the same in 1.4.

**Comment by eirslett** [comment]
I guess you could do this yourself in `pom.xml`: only enable the execution of npm install when `${settings.offline}` is false. (I think that's the name of the property).
The problem is that this plugin doesn't care what the node/npm scripts do, so there is no way of automatically knowing whether or not running them will lead to network calls. As a developer, you have this knowledge, so you can set up the pom.xml file for it.

**Comment by Deevian** [comment]
I imagined it would be something of the sort, but since the `npm` goal is executing the install by default, it would useful for the plugin to do this. Still, that's fair enough -- I'll set it up in the pom.

**Comment by javahelp** [comment]
> I guess you could do this yourself in `pom.xml`: only enable the execution of npm install when `${settings.offline}` is false. (I think that's the name of the property).
> The problem is that this plugin doesn't care what the node/npm scripts do, so there is no way of automatically knowing whether or not running them will lead to network calls. As a developer, you have this knowledge, so you can set up the pom.xml file for it.

What would this config look like please?
I don't see a config for "only execute if true".
Or are we expected to set up an entire Maven Profile for this?
