### ISSUE TITLE
Feature request: allow node version to accept codename

### ISSUE THREAD

**Issue by RGTGT** [eirslett/frontend-maven-plugin#641]
Hello,

Using frontend-maven-plugin 1.5. I tried to specify the node version by its codename based on the folders we find [here](https://nodejs.org/dist/): latest-boron

`
<configuration>
              <nodeVersion>latest-boron</nodeVersion>
</configuration>
`

I suspect the plugin is expecting a version in vXXX format since I get a

> java.lang.NumberFormatException: For input string: "latest-boron"

I think it would be nice to be able to use codenames since it would allow to always retrieve the latest LTS version for example.

**Comment by eirslett** [comment]
Using the latest version would be kind of an anti-feature (as apposed to locking down version numbers), because sometimes there are regressions that appear in newer versions of node.js, and you don't want them to break the build. So that's why you want the build to run the same version of node.js both on your laptop and on CI; so if something breaks you don't have to worry about node versions.

**Comment by esphen** [comment]
The flip side of this argument is that since you are not able to specify for example `latest-v6.x`, then you have to manually go and update versions for each and every project every time there is a nodejs update. This is very tedious and ensures that essential security patches for node are not rolled out to projects that aren't prioritized, i.e. legacy projects.

If users want the feature of automatically getting security updates with the tradeoff having builds potentially break due to node regressions, should they really not be given that option? It would really save on maintainance costs when a lot of projects use this plugin.

**Comment by eirslett** [comment]
It's correct that you'll have to update node versions manually, instead of getting them "for free". What you can do if you have many projects is to write a script that git clones all your repositories, regexes its way into the pom.xml files and updates `<nodeVersion>`, commits and pushes.

**Comment by esphen** [comment]
Sure, but you hear what you're saying, right? Instead of people getting security fixes for free through this library, you propose everyone write complicated scripts. 99% of people will not do this.

nvm already allows you to specify a 8.x version by setting `8` in the `.nvmrc`.
