### ISSUE TITLE
stderr output does not imply error

### ISSUE THREAD

**Issue by cowwoc** [eirslett/frontend-maven-plugin#833]
Looking at https://github.com/webpack/webpack-cli/issues/1017#issuecomment-517569237 and the various examples mentioned at https://github.com/eirslett/frontend-maven-plugin/issues/584 it's pretty clear that flagging all stderr output as `[ERROR]` is a but, not a feature.

Please add an option to disable this feature... ideally by default. At the very least we should be able to disable it if we want to.

Secondly, is there any chance of us getting colored output? Maven 3.5.0+ outputs ANSI colors. Yarn outputs ANSI colors. But when we run Yarn through this plugin we lose all colors. Instead of redirecting output to the log, would it help to output to stdout, stderr directly instead?

**Comment by cowwoc** [comment]
@eirslett So #834 fixes the first part of this issue. Do you have any ideas about the second part (color support)?

**Comment by eirslett** [comment]
I'm not so sure about the colors... also not too happy about forwarding stdout directly to system.out, since it's useful to use Maven's logging abstraction - potentially users might have some custom logging configuration, which will be respected with this plugin, when it uses Maven's logging abstraction.
Maybe Maven has changed its plugin API in 3.5.0 to support colors?
