### ISSUE TITLE
Wrong binary downloaded on AIX Machines

### ISSUE THREAD

**Issue by atomicpages** [eirslett/frontend-maven-plugin#839]
For AIX machines the wrong binary is getting downloaded. I see there's some handling for OS architecture and types in `Platform.java` but nothing specifically for AIX `ppc64` so the generic linux node package is getting downloaded. To repro use any AIX machine with a standard config.

I'm happy to submit a PR since I have access to an AIX box 😄

**Comment by bmarwell** [comment]
@atomicpages did you ever find time to create a PR?

**Comment by eirslett** [comment]
I've never even heard about AIX machines, and no access to one for testing purposes. Feel free to send a PR though! As long as it doesn't break for the other architectures that are supported (Windows, Macos, Linux, Alpine, ARM...)

**Comment by bmarwell** [comment]
No worries! AIX is a unix operating system, maintained by IBM for the ppc64 (note: not the ppc64le) architecture. It is mostly used by large companies, because you can rent processors and only pay for the active ones.
There are 31(!) and 64bit implementations, but 31 is dead now. 

If @atomicpages doesn’t come up with one, I will.

**Comment by bmarwell** [comment]
@eirslett would you also consider my other PR for pnpm support please?
