### ISSUE TITLE
If installationDirectory is not present use OS Path.

### ISSUE THREAD

**Issue by effusion** [eirslett/frontend-maven-plugin#840]
Hello Guys,

we are currently using your plugin to bundle a react app into spring boot. I notice some strange behaviour

**Do you want to request a _feature_ or report a _bug_?**

I would say it's a feature request because according to the code it was designed this way. I just used the examples provided on the main page.

**What is the current behavior?**

When we where trying to build the App with Yarn without installing it through the plugin, it was never able to find the executables for yarn. The error message showed a rather strange path which was within the node installation directory. Since we run on an internal Jenkins within a bank, we use the binaries for yarn and node which are installed on the build node and because itself has no access to the internet. 

**If the current behavior is a bug, please provide the steps to reproduce.**

Just try to build an application without the install part like
`<execution>
    <id>yarn install</id>
    <goals>
        <goal>yarn</goal>
    </goals>
    <configuration>
         
        <arguments>install</arguments>
    </configuration>
</execution>`

**What is the expected behavior?**

I would expect the plugin to use the path of the underlying OS to find executables if the <installationDirectory> is not provided. Generally i want the build server to handle the version of node rather than configure it in the plugin.

**Please mention your frontend-maven-plugin and operating system version.**

Maven: 3.6.1
Plugin Version: 1.8.0
OS: Windows 10 for Dev, RHEL on Build Node.

**Comment by eirslett** [comment]
This is by design. This plugin is never supposed to use the system installation of node/npm/yarn, because it has no guarantees about which version of the tools are installed - which means you will have builds that are not reproducible, for example if the build works on a developer machine, but not on your Jenkins, because Jenkins has an older version of node.js. That is why the plugin always downloads the correct version of node/npm/yarn as you have specified in pom.xml.

If you really want to use the global node/npm/yarn, I suggest that you use exec-maven-plugin instead!
